"""
Kept so that `import sabrina_compare` keeps working.

The audit moved to `smile_partners/sabrina/`. Each client now owns a folder of
its own — its portal readers, its breakdown builder and, for Smile Partners,
the Sabrina sheet — so a change made for one client cannot reach another.
Every name this module used to define is re-exported below, unchanged.
"""

# flake8: noqa: F401

from smile_partners.sabrina.common import (
    _BLANKS,
    _DEBUG,
    _UNLIMITED_MAX,
    log,
)
from smile_partners.sabrina.spec import (
    CORE_FIELD_KEYS,
    _AGE_LIMIT_CODES,
    _ASPECT_SECTION,
    _BENEFIT_ASPECTS,
    _CRITICAL_KEYS,
    _HISTORY_CODES,
    _NO_FREQUENCY_CODES,
    _SPEC,
    _aspect_applies,
    _build_aspect_spec,
    core_fields,
)
from smile_partners.sabrina.vocabulary import (
    _CARRIER_BRANDS,
    _COB_METHODS,
    _DATE_FORMATS,
    _FREQ_CLAUSE_SPLIT,
    _FREQ_COMPACT_RE,
    _FREQ_NOT_COVERED,
    _FREQ_NO_LIMIT_WORDS,
    _FREQ_PREDETERMINATION,
    _FREQ_PROSE_RE,
    _FREQ_UNLIMITED,
    _FREQ_WORD_COUNTS,
    _HISTORY_DASHES,
    _HISTORY_NONE,
    _MASK_RE,
    _MONTHS,
    _NAME_SUFFIXES,
    _NO,
    _YES,
    _addr_tokens,
    _agelimit_lower,
    _blank,
    _blank_for,
    _blank_means_no_limit,
    _carrier_brand,
    _clause_age_range,
    _coalesce_keys,
    _frequency_note,
    _history_dates,
    _norm_id,
    _norm_name,
    _norm_network,
    _norm_text,
    _num_agelimit,
    _num_cob,
    _num_date,
    _num_frequency,
    _num_history,
    _num_money,
    _num_month,
    _num_pct,
    _num_yesno,
    _parse_single_frequency,
    _select_frequency_clause,
    _visible_part,
)
from smile_partners.sabrina.parser import (
    _ALL_LABELS,
    _BOILERPLATE_RE,
    _FREQ_RE,
    _LABELS_BY_FIRST,
    _MARKERS,
    _MIN_MARKERS,
    _NON_VALUES,
    _OTHER_SHEET_LABELS,
    _SEP_RE,
    _STOP_LABELS,
    _TRIM,
    _anchor_line,
    _any_label_at,
    _capture_benefit_rows,
    _classify_row_cells,
    _find_value,
    _label_span,
    _looks_like_value,
    _norm_label,
    _pick_cell,
    _refine_inline,
    _reflow_wrapped,
    _split_lines,
    is_sabrina_pdf,
    parse_sabrina_pdf,
    parse_sabrina_text,
    sabrina_marker_count,
)
from smile_partners.sabrina.compare import (
    _ADDR_OVERLAP,
    _MONEY_TOLERANCE,
    _PCT_TOLERANCE,
    _compare,
)
from smile_partners.sabrina.carriers.cigna import (
    _CIGNA_BLANK_WHEN_NOT_COVERED,
    _CIGNA_FL_CODES,
    _cigna_annual_max_classes,
    _cigna_code_override,
    _cigna_export,
    _cigna_fl_row,
    _cigna_oon_benefits,
    _cigna_ortho_deductible,
    _cigna_preventive_pct,
    _cigna_procedure_not_covered,
)
from smile_partners.sabrina.portal import (
    _DERIVED,
    _lifetime_belongs_elsewhere,
    _network_coverage,
    _network_pays,
    _ortho_is_covered,
    _pct_from_procs,
    _portal_breakdown,
    _portal_cob,
    _portal_in_network,
    _portal_normalized,
    _portal_oon_benefits,
    _portal_ortho_age,
    _portal_ortho_ded,
    _portal_ortho_ded_met,
    _portal_ortho_max,
    _portal_ortho_used,
    _portal_prev_in_max,
    _portal_value,
    _portal_yearly_max_paid,
    _procfield_from_procs,
)
from smile_partners.sabrina.audit import (
    STATUS_MATCH,
    STATUS_MISMATCH,
    STATUS_MISSING_IN_SABRINA,
    STATUS_NOT_COMPARABLE,
    STATUS_NOT_IN_PORTAL,
    STATUS_NOT_STATED,
    _age_from_dob,
    audit_sabrina_pdf,
    compare_sabrina_to_portal,
)
from smile_partners.sabrina.cli import (
    _cli,
)
